name: Surface Water Quality

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

# Default permission for all jobs
permissions:
  contents: read

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./NodeJS

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Pages
        uses: actions/configure-pages@v6

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: npm
          cache-dependency-path: NodeJS/package-lock.json

      - name: Install packages
        run: npm ci

      - name: Build app
        run: npm run build --if-present
        env:
          CI: ""

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: ./NodeJS/build

  deploy:
    if: github.event_name != 'pull_request'
    needs: build
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
